# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each half day)
  # schedule: [{ cron: "0 0,12 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["neko"] }
jobs:
  job1:
    name: 📐 Update metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🌐 general
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/general.svg
          # Options
          user: OverflowCat
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # half-year
          repositories_skipped: ${{ secrets.SKIPPED_REPOS }},OverflowCat/vim-flypy,OverflowCat/lemmy #,${{ secrets.LARGE }}
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: recently-used, most-used
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 888
          plugin_languages_analysis_timeout: 30
          plugin_languages_analysis_timeout_repositories: 9
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage
          plugin_languages_ignored: pdf, epub, mobi, zip, rar, 7z, Dhall, css, text, html, rtf, YAML, json, dockerfile, makefile, qmake, ejs, Jupyter Notebook
          plugin_languages_other: false
          # plugin_languages_aliases: Svelte:TypeScript
          plugin_languages_aliases: RenderScript:Rust # temp solution until Rust as RenderScript bug is fixed
          plugin_languages_limit: 16
          plugin_languages_threshold: 0%
          plugin_languages_indepth_custom: E011011101001/Twitter-Block-With-Love
          # plugin_tweets: yes
          # plugin_tweets_token: ${{ secrets.TWITTER_SECRET }}
          # plugin_tweets_limit: 2
          # plugin_tweets_user: .user.twitter
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          # plugin_activity: yes
          # plugin_activity_limit: 5
          # plugin_activity_days: 31
          # plugin_activity_filter: issue, pr, release, fork, review, ref/create
          # plugin_discussions: yes
          # plugin_discussions_categories_limit: 8
          plugin_calendar: yes
          plugin_calendar_limit: 0
          plugin_code: yes
          plugin_code_languages: haskell, python, rust, go, c, javascript, typescript
          plugin_code_load: 345
          plugin_followup: yes
          plugin_followup_indepth: yes
      - name: ⌛ wakatime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_timezone: Asia/Shanghai
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_SECRET }}
          plugin_wakatime_days: 15
          plugin_wakatime_limit: 5 # Display limit (entries per graph)
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os #, projects, projects-graphs
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
      - name: 📶 blogposts
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          filename: metrics/rss.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_rss: true
          plugin_rss_source: https://blog.xinshijiededa.men/atom.xml
          plugin_rss_limit: 6
      - name: 🧑‍💻 leetcode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/leetcode.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
      - name: 🤼 followers
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          filename: metrics/followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "metadata"
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 60
          plugin_people_size: 80
