# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each half day)
  schedule: [{cron: "0 0,12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["neko"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: OverflowCat
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          repositories_skipped: ${{ secrets.SKIPPED_REPOS }},OverflowCat/vim-flypy
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 666
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage
          plugin_languages_ignored: Dhall, text, html, rtf, YAML, json, dockerfile, makefile, qmake, ejs, Jupyter Notebook
          # plugin_languages_aliases: Svelte:TypeScript
          plugin_languages_aliases: RenderScript:Rust # temp solution until Rust as RenderScript bug is fixed
          plugin_languages_limit: 16
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 28
          plugin_languages_recent_load: 888
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          # plugin_tweets: yes
          # plugin_tweets_token: ${{ secrets.TWITTER_SECRET }}
          # plugin_tweets_limit: 2
          # plugin_tweets_user: .user.twitter
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          # plugin_activity: yes
          # plugin_activity_limit: 5
          # plugin_activity_days: 31
          # plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
          # plugin_wakatime: yes
          # plugin_wakatime_token: ${{ secrets.WAKATIME_SECRET }}
          # plugin_wakatime_days: 14
          # plugin_wakatime_limit: 5
          # plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          # plugin_wakatime_url: https://wakatime.com
          # plugin_wakatime_user: current
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 120
          plugin_people_size: 80
